apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-fuse
  labels:
    app: ubuntu-fuse
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    securityContext:
      privileged: true
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
